# Generated by Django 3.0.dev20190708065308 on 2019-07-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20190719_0143'),
    ]

    operations = [

        migrations.AddField(
            model_name='file',
            name='height_im',
            field=models.CharField(default=100, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='width_im',
            field=models.CharField(default=100, max_length=4),
            preserve_default=False,
        ),
    ]
